package com.whalecar.domain;

// Generated 2013-7-4 14:32:43 by Hibernate Tools 3.4.0.CR1

/**
 * CarModelLv3 generated by hbm2java
 */
public class CarModelLv3 implements java.io.Serializable {

	private Integer id;
	private int carModelLv2;
	private String shortName;
	private String fullName;
	private String colorOutsideCollection;
	private String colorInsideCollection;
	private long factoryPrice;
	private Integer orderIndex;
	private String flagUseable;

	public CarModelLv3() {
	}

	public CarModelLv3(int carModelLv2, String shortName, String fullName,
			String colorOutsideCollection, String colorInsideCollection,
			long factoryPrice, String flagUseable) {
		this.carModelLv2 = carModelLv2;
		this.shortName = shortName;
		this.fullName = fullName;
		this.colorOutsideCollection = colorOutsideCollection;
		this.colorInsideCollection = colorInsideCollection;
		this.factoryPrice = factoryPrice;
		this.flagUseable = flagUseable;
	}

	public CarModelLv3(int carModelLv2, String shortName, String fullName,
			String colorOutsideCollection, String colorInsideCollection,
			long factoryPrice, Integer orderIndex, String flagUseable) {
		this.carModelLv2 = carModelLv2;
		this.shortName = shortName;
		this.fullName = fullName;
		this.colorOutsideCollection = colorOutsideCollection;
		this.colorInsideCollection = colorInsideCollection;
		this.factoryPrice = factoryPrice;
		this.orderIndex = orderIndex;
		this.flagUseable = flagUseable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCarModelLv2() {
		return this.carModelLv2;
	}

	public void setCarModelLv2(int carModelLv2) {
		this.carModelLv2 = carModelLv2;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getColorOutsideCollection() {
		return this.colorOutsideCollection;
	}

	public void setColorOutsideCollection(String colorOutsideCollection) {
		this.colorOutsideCollection = colorOutsideCollection;
	}

	public String getColorInsideCollection() {
		return this.colorInsideCollection;
	}

	public void setColorInsideCollection(String colorInsideCollection) {
		this.colorInsideCollection = colorInsideCollection;
	}

	public long getFactoryPrice() {
		return this.factoryPrice;
	}

	public void setFactoryPrice(long factoryPrice) {
		this.factoryPrice = factoryPrice;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getFlagUseable() {
		return this.flagUseable;
	}

	public void setFlagUseable(String flagUseable) {
		this.flagUseable = flagUseable;
	}

}
