package com.whalecar.domain;

import java.io.Serializable;

// Generated 2013-7-5 22:40:38 by Hibernate Tools 3.4.0.CR1

/**
 * CarModelLv1 generated by hbm2java
 */
public class CarModelLv1 implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7803186654696850258L;
	private Integer id;
	private int carBrand;
	private Integer carSubBrand;
	private String cname;
	private String ename;
	private String imgPath;
	private Integer orderIndex;
	private String flagUseable;

	public CarModelLv1() {
	}

	public CarModelLv1(int carBrand, String cname, String ename,
			String imgPath, String flagUseable) {
		this.carBrand = carBrand;
		this.cname = cname;
		this.ename = ename;
		this.imgPath = imgPath;
		this.flagUseable = flagUseable;
	}

	public CarModelLv1(int carBrand, Integer carSubBrand, String cname,
			String ename, String imgPath, Integer orderIndex, String flagUseable) {
		this.carBrand = carBrand;
		this.carSubBrand = carSubBrand;
		this.cname = cname;
		this.ename = ename;
		this.imgPath = imgPath;
		this.orderIndex = orderIndex;
		this.flagUseable = flagUseable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCarBrand() {
		return this.carBrand;
	}

	public void setCarBrand(int carBrand) {
		this.carBrand = carBrand;
	}

	public Integer getCarSubBrand() {
		return this.carSubBrand;
	}

	public void setCarSubBrand(Integer carSubBrand) {
		this.carSubBrand = carSubBrand;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getFlagUseable() {
		return this.flagUseable;
	}

	public void setFlagUseable(String flagUseable) {
		this.flagUseable = flagUseable;
	}

}
