package com.whalecar.domain;

import java.io.Serializable;
import java.util.List;

// Generated 2013-7-5 22:40:38 by Hibernate Tools 3.4.0.CR1

/**
 * DicCity generated by hbm2java
 */
public class DicCity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6251263106374331353L;
	private Integer id;
	private String provinceCname;
	private String provinceEname;
	private String cityCname;
	private String cityEname;
	private Integer orderIndex;
	private String flagUseable;
    private List<DicArea> AreaList;


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvinceCname() {
		return this.provinceCname;
	}

	public void setProvinceCname(String provinceCname) {
		this.provinceCname = provinceCname;
	}

	public String getProvinceEname() {
		return this.provinceEname;
	}

	public void setProvinceEname(String provinceEname) {
		this.provinceEname = provinceEname;
	}

	public String getCityCname() {
		return this.cityCname;
	}

	public void setCityCname(String cityCname) {
		this.cityCname = cityCname;
	}

	public String getCityEname() {
		return this.cityEname;
	}

	public void setCityEname(String cityEname) {
		this.cityEname = cityEname;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getFlagUseable() {
		return this.flagUseable;
	}

	public void setFlagUseable(String flagUseable) {
		this.flagUseable = flagUseable;
	}

    public List<DicArea> getAreaList() { return AreaList;}

    public void setAreaList(List<DicArea> areaList) { AreaList = areaList; }

}
