package com.whalecar.domain;

// Generated 2013-7-4 14:32:43 by Hibernate Tools 3.4.0.CR1

/**
 * DicCity generated by hbm2java
 */
public class DicCity implements java.io.Serializable {

	private Integer id;
	private String provinceCname;
	private String provinceEname;
	private String cityCname;
	private String cityEname;
	private Integer orderIndex;
	private String flagUseable;

	public DicCity() {
	}

	public DicCity(String provinceCname, String provinceEname,
			String cityCname, String cityEname, String flagUseable) {
		this.provinceCname = provinceCname;
		this.provinceEname = provinceEname;
		this.cityCname = cityCname;
		this.cityEname = cityEname;
		this.flagUseable = flagUseable;
	}

	public DicCity(String provinceCname, String provinceEname,
			String cityCname, String cityEname, Integer orderIndex,
			String flagUseable) {
		this.provinceCname = provinceCname;
		this.provinceEname = provinceEname;
		this.cityCname = cityCname;
		this.cityEname = cityEname;
		this.orderIndex = orderIndex;
		this.flagUseable = flagUseable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProvinceCname() {
		return this.provinceCname;
	}

	public void setProvinceCname(String provinceCname) {
		this.provinceCname = provinceCname;
	}

	public String getProvinceEname() {
		return this.provinceEname;
	}

	public void setProvinceEname(String provinceEname) {
		this.provinceEname = provinceEname;
	}

	public String getCityCname() {
		return this.cityCname;
	}

	public void setCityCname(String cityCname) {
		this.cityCname = cityCname;
	}

	public String getCityEname() {
		return this.cityEname;
	}

	public void setCityEname(String cityEname) {
		this.cityEname = cityEname;
	}

	public Integer getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	public String getFlagUseable() {
		return this.flagUseable;
	}

	public void setFlagUseable(String flagUseable) {
		this.flagUseable = flagUseable;
	}

}
