package com.whalecar.domain;

// Generated 2013-7-5 22:40:38 by Hibernate Tools 3.4.0.CR1

/**
 * Shop generated by hbm2java
 */
public class Shop implements java.io.Serializable {

	private Integer id;
	private String shopName;
	private String shopAddress;
	private String shopTel;
	private String shopEmail;
	private int shopCity;
	private long shopLocationLongtude;
	private long shopLocationDimensiong;
	private String loginName;
	private String loginPassword;
	private String flagUseable;
	private int carBrand;
	private int carSubBrand;

	public Shop() {
	}

	public Shop(String shopName, String shopAddress, String shopTel,
			String shopEmail, int shopCity, long shopLocationLongtude,
			long shopLocationDimensiong, String loginName,
			String loginPassword, String flagUseable) {
		this.shopName = shopName;
		this.shopAddress = shopAddress;
		this.shopTel = shopTel;
		this.shopEmail = shopEmail;
		this.shopCity = shopCity;
		this.shopLocationLongtude = shopLocationLongtude;
		this.shopLocationDimensiong = shopLocationDimensiong;
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.flagUseable = flagUseable;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopAddress() {
		return this.shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	public String getShopTel() {
		return this.shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	public String getShopEmail() {
		return this.shopEmail;
	}

	public void setShopEmail(String shopEmail) {
		this.shopEmail = shopEmail;
	}

	public int getShopCity() {
		return this.shopCity;
	}

	public void setShopCity(int shopCity) {
		this.shopCity = shopCity;
	}

	public long getShopLocationLongtude() {
		return this.shopLocationLongtude;
	}

	public void setShopLocationLongtude(long shopLocationLongtude) {
		this.shopLocationLongtude = shopLocationLongtude;
	}

	public long getShopLocationDimensiong() {
		return this.shopLocationDimensiong;
	}

	public void setShopLocationDimensiong(long shopLocationDimensiong) {
		this.shopLocationDimensiong = shopLocationDimensiong;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public String getFlagUseable() {
		return this.flagUseable;
	}

	public void setFlagUseable(String flagUseable) {
		this.flagUseable = flagUseable;
	}

	public int getCarBrand() {
		return carBrand;
	}

	public void setCarBrand(int carBrand) {
		this.carBrand = carBrand;
	}

	public int getCarSubBrand() {
		return carSubBrand;
	}

	public void setCarSubBrand(int carSubBrand) {
		this.carSubBrand = carSubBrand;
	}
}
