package com.whalecar.domain;

// Generated 2013-7-5 22:40:38 by Hibernate Tools 3.4.0.CR1

/**
 * ShopStock generated by hbm2java
 */
public class ShopStock implements java.io.Serializable {

	private Integer id;
	private int shop;
	private int carModelLv3;
	private int carOutsideColor;
	private int carInsideColor;
	private String carAddition;
	private long carPrice;
	private int carOnOrderNum;
	private int carOnHandeNum;

	public ShopStock() {
	}

	public ShopStock(int shop, int carModelLv3, int carOutsideColor,
			int carInsideColor, long carPrice, int carOnOrderNum,
			int carOnHandeNum) {
		this.shop = shop;
		this.carModelLv3 = carModelLv3;
		this.carOutsideColor = carOutsideColor;
		this.carInsideColor = carInsideColor;
		this.carPrice = carPrice;
		this.carOnOrderNum = carOnOrderNum;
		this.carOnHandeNum = carOnHandeNum;
	}

	public ShopStock(int shop, int carModelLv3, int carOutsideColor,
			int carInsideColor, String carAddition, long carPrice,
			int carOnOrderNum, int carOnHandeNum) {
		this.shop = shop;
		this.carModelLv3 = carModelLv3;
		this.carOutsideColor = carOutsideColor;
		this.carInsideColor = carInsideColor;
		this.carAddition = carAddition;
		this.carPrice = carPrice;
		this.carOnOrderNum = carOnOrderNum;
		this.carOnHandeNum = carOnHandeNum;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getShop() {
		return this.shop;
	}

	public void setShop(int shop) {
		this.shop = shop;
	}

	public int getCarModelLv3() {
		return this.carModelLv3;
	}

	public void setCarModelLv3(int carModelLv3) {
		this.carModelLv3 = carModelLv3;
	}

	public int getCarOutsideColor() {
		return this.carOutsideColor;
	}

	public void setCarOutsideColor(int carOutsideColor) {
		this.carOutsideColor = carOutsideColor;
	}

	public int getCarInsideColor() {
		return this.carInsideColor;
	}

	public void setCarInsideColor(int carInsideColor) {
		this.carInsideColor = carInsideColor;
	}

	public String getCarAddition() {
		return this.carAddition;
	}

	public void setCarAddition(String carAddition) {
		this.carAddition = carAddition;
	}

	public long getCarPrice() {
		return this.carPrice;
	}

	public void setCarPrice(long carPrice) {
		this.carPrice = carPrice;
	}

	public int getCarOnOrderNum() {
		return this.carOnOrderNum;
	}

	public void setCarOnOrderNum(int carOnOrderNum) {
		this.carOnOrderNum = carOnOrderNum;
	}

	public int getCarOnHandeNum() {
		return this.carOnHandeNum;
	}

	public void setCarOnHandeNum(int carOnHandeNum) {
		this.carOnHandeNum = carOnHandeNum;
	}

}
